[tool.poetry]
name = "benbenbang"
version = "0.1.0"
description = ""
authors = ["benbenbang <bn@benbenbang.io>"]

[tool.poetry.dependencies]
python = "3.9.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
